{% set version = "3.3.9" %}

package:
  name: fftw
  version: {{ version }}

source:
  url: https://www.fftw.org/fftw-{{ version }}.tar.gz
  sha256: bf2c7ce40b04ae811af714deb512510cc2c17b9ab9d6ddcf49fe4487eea7af3d

build:
  number: 2
  run_exports:
    - {{ pin_subpackage('fftw', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - perl                 # [not win]
    - cmake                # [win]
    - ninja                # [win]
    - make                 # [not win]
    - libtool              # [not win]

test:
  commands:
    - exit $(test -f ${PREFIX}/lib/libfftw3f.a)          # [not win]
    - exit $(test -f ${PREFIX}/lib/libfftw3.a)           # [not win]
    - exit $(test -f ${PREFIX}/lib/libfftw3l.a)          # [not win]
    - exit $(test -f ${PREFIX}/lib/libfftw3f_threads.a)  # [not win]
    - exit $(test -f ${PREFIX}/lib/libfftw3_threads.a)   # [not win]
    - exit $(test -f ${PREFIX}/lib/libfftw3l_threads.a)  # [not win]

    # Verify headers are installed
    - test -f ${PREFIX}/include/fftw3.h                  # [not win]
    - if not exist %LIBRARY_INC%\\fftw3.h exit 1         # [win]

    # Verify shared libraries are installed
    {% set fftw_libs = [
            "libfftw3",
            "libfftw3_threads",
            "libfftw3f",
            "libfftw3f_threads",
            "libfftw3l",
            "libfftw3l_threads",
    ] %}

    {% set fftw_libs = ["fftw3f", "fftw3"] %}

    {% for base in fftw_libs %}
    - if not exist %LIBRARY_LIB%\\{{ base }}.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\{{ base }}.dll exit 1  # [win]
    {% endfor %}

about:
  home: https://fftw.org
  license: GPL-2.0
  license_file: COPYING
  license_family: GPL
  summary: "The fastest Fourier transform in the west."
  description: |
    FFTW is a C subroutine library for computing the discrete Fourier transform (DFT)
    in one or more dimensions, of arbitrary input size, and of both real and complex
    data (as well as of even/odd data, i.e. the discrete cosine/sine transforms or
    DCT/DST). We believe that FFTW, which is free software, should become the FFT
    library of choice for most applications.
  dev_url: https://github.com/FFTW/fftw3
  doc_url: https://fftw.org/#documentation

extra:
  recipe-maintainers:
    - alexbw
    - jakirkham
    - jjhelmus
    - grlee77
    - jschueller
