travis:
  secure:
    BINSTAR_TOKEN: WU1N/yLPTMMu1l5yuBVNE7LKPQhR/muCEYvmHd0AQfKpOBsVaIl834T216oVEa/CfaoBTZ2wha8gU8fyrdBERs6WPSKx8nc3NnVA5JPfKTvRbP+5GAZnaTjvhIy7Om58KV4CPybtGNNAriS/o8oA8+0lM3jQcDAZY70mRp77JRoiOnuThY5ejwNe9EzoIB3UV8mOG1OkeOkqaE5mtedHeuw2ITSyi260uCuuew+JlpRxPf6sgsFi49wEYPU67nJ5QG/VvjRrN4oXeVQdSaQ2C7DU0M8oAmTyjCrwGY1Pl8nMnu96TiU3HUav+NiTeSivOPzqsDeJCrPstYo/VBcSkHR5UeBl+GnXvXD16adYNjqc9y8nztGQW8NiHmT6Yrlyf5jJEcerZr6J2FBYQCvJNkrCAgM1RlgmqdsScpFCxGv1ev7dmveLjeE4du0dI44Lq0M1vH6V2GY0hlyoECN0ibhqqK14FeqkMIZ0mQBPQxE5tOTZCmH/SHsj52PMXPEhrNhsMgYjPRyqS8dYajvnZv4Ds9MwTyZJAs7C7eRdzgkboyfdT5iO6xbaUE/k5vT8P0pSjkZK56LuEQd5AJdj+/Blo7Ulhty2+daNcl0a0sYgMFeHZuvGzQOQ1LeWHyvHGSQlZP++xWRJ8kEzrAiML/Yqyg0N9xLn5FSQSLqcYm8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
