travis:
  secure:
    BINSTAR_TOKEN: ojvIjMGjD7DrUPa4kxyEJDkPPwGudXxCS1bf7/5NhJMSvxre15JKMOlCnHh0wRu9tOb0AYA0qDKGVMFqyiCA4bJgMrQ6sKTNAadaSYLJrFBR4Lx8pKw2fKHS6a3PvZwaRbVHpbGq4N8gOhuKkOQiIJ5sTH37sknzg/GM9jc2YWnSIcy26AaBeRglEcIAmvOppiR1l/jZelwM25d0cxQXDlIf07ra7Nm1/YrqIWqQlgpxLKu1QNXF/jY030x6NXRCDaFSSAiS48rPyxtbdkyP6pOd5TlWYxXeID4PYEzQWn5lhJq28gb0ZCXAmMdXXNNeFj7RWNmzqiNcmtvNLfgH95O2yxsHMdENPLSChVvWj1DHZkVGRV3XowHDoLgTsMi+UG908S7zNhtkp2Ty5jAotOxl16BIKXGwIbJGFpu5/9HX5HlhiSqoV8f3C3ZHoj/cBdMW/8dERscWFt7uNQVBt0VhOHif86v0zlKYVNZUHBeWpQqQ3P4ctkReh5XyPs+QsX47b6sgfzjdC/OApN/rmpEVijViLt1ARUp6qj7RPnUi8bWrC0rUncBSss132QDj8uDNFj/MqjHHlmxmIFF9PZIYzqi0dZN71MZwb7XMIOzLuxLxQmDV0ru635EeEeiL5yR/nyp8eCrvoZIxdXuNJN8rd6mQPW87EZxXIi6J8Sw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
