travis:
  secure:
    BINSTAR_TOKEN: QJKtQMqLfk15f0jpesmVozy10BPTX4NzpDsJBDlECQkfi8uutkxdo6BKoTjUPI6OEE321B+eHRH34Qae28XWV0MtG6IOhsIaB6J8f1lWUfs+KgUKVils8HYBey5KuliMEDRrH17VzVqvjWcxPeyhdiqio45qZZVEoZM7oIGN+VE5stxmIV56ESKLI8x1FS96IExHXsFez3m5TU0ygmV89ps4viAoBkA3I1i74V4eIcA8BGw4FkFyrCN4xW1MFLm+Ph+HqZn1qb3QClqX5/2KOUldU3ml2WMZklpfVnHfLVbnDVVxdjCe+cgzLzuSxtCXrkT0ij9Oa9ezpNr+eFSUBjsjA3L0LvS62S2wUOrDEhDQm4Lo4k81cW22ogj7JtROOp2UYz6v2OvxjOB6TVmTJHFxxC8Bvwt3O8OTYtRdqotOaXOCWSi1YgAM3Q1EHWXo6ypKsSZDM9Z/5H56MU1XOyOWuQR62poGRGTeYxrwYu4NgWU4A76XWeOzYtoBTTws5dvCioHglMRAKnCB1SXQKCUQykdCW2NuNQIx8zV8a58EfY6mss04j0SUQaDMna3IekiK0Y57I7vRzLPUr8qsGI6l3ssyBTeSaLZLxs2iqaAi7K/fOTwcW9qaOY9QikNBomvaesN86Y1Unp4YtJcrum1VUfTdq7hNe4X29ooETOg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
